# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4238142dc35cf5711c28d7b145aac217344c2d3619ae7220e84b1c9414ed1d5384c9c10d3fb9ea1afa275f3d9c601130f57d22187cd014ad6c03be4869d1cb9e

test:
  secret_key_base: f1bb09ebcfddee7d2d7ab1a2806fdd1dd88c436cd21126bebe821585fd0eb4b50e91180eea5459ccc45558e571971a5f5c29bad9347dc8e2a88efb469e72e406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
